spring.application.name=equipment-rental

spring.datasource.url=jdbc:postgresql://localhost:5433/equipment_db

spring.datasource.username=dev_user
spring.datasource.password=super_secret_dev_password


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true